;; ************************************************************************** ;;
;;                                                                            ;;
;;                                                        :::      ::::::::   ;;
;;   99-adminer.ini                                     :+:      :+:    :+:   ;;
;;                                                    +:+ +:+         +:+     ;;
;;   By: ghenriqu <ghenriqu@student.42porto.com>    +#+  +:+       +#+        ;;
;;                                                +#+#+#+#+#+   +#+           ;;
;;   Created: 2026/08/01 14:21:02 by ghenriqu          #+#    #+#             ;;
;;   Updated: 2026/08/01 14:21:09 by ghenriqu         ###   ########.fr       ;;
;;                                                                            ;;
;; ************************************************************************** ;;

expose_php = Off

session.cookie_httponly = 1
session.cookie_secure   = 1
session.cookie_samesite = Strict

post_max_size       = 32M
upload_max_filesize = 32M
max_execution_time  = 300
