# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ghenriqu <ghenriqu@student.42porto.com>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/07/28 00:00:00 by ghenriqu          #+#    #+#              #
#    Updated: 2026/07/28 00:00:00 by ghenriqu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

bind 0.0.0.0
protected-mode yes
port 6379

daemonize no
supervised no

logfile ""
loglevel notice

save ""
appendonly no
dir /var/lib/redis

maxmemory 256mb
maxmemory-policy allkeys-lru
